# Generated by Django 5.1.7 on 2025-03-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_location_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='registered_location',
            field=models.BooleanField(default=False),
        ),
    ]
