# Generated by Django 5.1.7 on 2025-03-27 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrevision',
            name='design_ownership',
            field=models.CharField(choices=[('SELF', 'We own the design.'), ('ELSE', 'Design is owned by someone else.')], default='SELF', max_length=255),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='finished_device',
            field=models.CharField(choices=[('NO', 'This is not a finished device.'), ('NONSHIPPABLE', 'This is or contains finished device(s), but is not yet shippable.'), ('SHIPPABLE', 'This is or contains finished device(s) and is shippable.')], default='NO', max_length=255),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='manufacturing_options',
            field=models.CharField(choices=[('SELF', 'Only we manufacture this part.'), ('ELSE', 'We source this part externally.'), ('BOTH', 'Both we and someone else are able to manufacture this part.')], default='SELF', max_length=255),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='purpose_and_scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='set_role_by_step',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DocumentRevisionAttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document_revision_attached_files/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentrevision')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevisionInputPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentrevision')),
                ('input_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevisionOutputPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentrevision')),
                ('outout_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevisionProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='document_revision_process_step_images/')),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentrevision')),
                ('roles', models.ManyToManyField(blank=True, to='organization.role')),
            ],
        ),
    ]
