# Generated by Django 5.1.7 on 2025-03-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_purpose_and_scope_documentrevision_process_purpose_and_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevisionPreviousRevisionActionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='previous_revision_disposition',
            field=models.TextField(default='foobar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='previous_revision_action_tags',
            field=models.ManyToManyField(blank=True, to='documents.documentrevisionpreviousrevisionactiontag'),
        ),
    ]
