# Generated by Django 5.1.7 on 2025-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentrevisionpreviousrevisionactiontag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='legacy_control_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
